runelite/wiki

- General-Features.md
Makes it clearer and more to-the-point.
> improve the instructions for using different settings with different accounts.

- Ground-Items.md
Feature was added but undocumented, see runelite/runelite#10912
> Document quantity filter

- FAQ.md
- General-Features.md
Step by step instructions for people trying to import settings as a multiple profile user, from the POV of a windows user. I don't have a mac/unix device to write it from the POV of them. Some one else can fill in those gaps.
> Windows: Add multiple profile import/use for advanced users

- FAQ.md
- My plugins are gone
- My loot tracker data is gone
- Transfer settings to new device/how to sync
> Add basic troubleshooting steps for commonly asked support questions

- Rejected-or-Rolled-Back-Features.md
Making a PR because I probably missed some stuff
> Update rejected features page to current statement

- Information-about-the-Plugin-Hub.md
> Update second screenshot in plugin hub info

- Jagex-Launcher-Development.md
- _Sidebar.md
~~I don't know how to make sure this page would show up under the dev section of the wiki sidebar. How do I do that?~~ thanks felanbird.
Instructions based on discord message by Ranseur <3.
> Add Jagex Launcher development instructions

- FAQ.md
This does not include how to run safe mode with a Jagex account, so if someone could chime in on how to do that, that'd be great.
My main goal with this PR is:
- Add clearer instructions for less tech savvy users
- Prepare to add a link in the main repo's issue template. Right now the issue template only includes instructions for Windows
> Add clearer safe mode instructions to FAQ

- GPU-FAQ.md
> GPU-FAQ: add win 11

- Chat-Commands.md
New screenshot that includes `LP`, `SW`, & `Pets`
Also reset to default hotkeys for the image
> Chat-Commands: Update settings example screenshot

- Troubleshooting-problems-with-the-client.md
I'm now satisfied that this fix works for Mullvad users. I've been unable to get this workaround to work for user's on other VPN's, but Mullvad users seem to always have it resolved.
> Troubleshooting: add mullvad VPN workaround

- FAQ.md
Fixes some incorrect Markdown formatting and adds some missing full stops
> FAQ: Improve consistency of full stops

- FAQ.md
I only thought of one, do we have any others we should add?
> FAQ: add more frequently asked questions

- XP-Updater.md
Add section with a description for the newer `RuneTracker` setting to enable/disable newly added support for `runetracker.org`
> Update XP-Updater.md - Add section and description for new RuneTracker setting

- Chat-Commands.md
Splitting this into two PRs that way objectively wrong data isn't on the wiki while the upstream PR awaits merge&release
#47
> Chat-Commands: add more raids variations

- Entity-Hider.md
Updated option names, specific behaviors, and added missing options.
> Update Entity-Hider.md with all current options

- Chat-Commands.md
these are the ones that already exist
> Chat-Commands: add dt2 variations

- Interface-Styles.md
Added documentation and image from blog for the "condense player options" in interface styles.
> Interface-Styles: added condense player options

- VarPlayers,-VarBits,-and-VarClients.md
should prevent anymore PRs being opened for hub usage, i'll let this sit as a PR for a little bit just in case someone has some amazing wording that's better than removing the section
> Vars: remove section on adding vars to core

- Chat-Commands.md
> Chat-Commands: add Lunar Chest variations

- Rejected-or-Rolled-Back-Features.md
https://secure.runescape.com/m=news/a=13/undead-pirates-tweaks-varlamore-cas--more?oldschool=1
> Rejected-or-Rolled-Back-Features: remove features that are now allowed

- Rejected-or-Rolled-Back-Features.md
This is basically the best way of phrasing it I could come up with, although maybe someone else can do better.
> Rejected-Features: add new rejected plugin

- Timers-&-Buffs.md
- Timers.md
For when https://github.com/runelite/runelite/pull/17662 gets merged.
The file name change is based on the client's code:
```java
menuItem.addActionListener(e -> LinkBrowser.browse("https://github.com/runelite/runelite/wiki/" + name.replace(' ', '-')));
```
> timers: rename to timers & buffs

- Chat-Commands.md
https://github.com/runelite/runelite/pull/18232
> chat commands: add bird's egg sacrifices kc

- Home.md
- _Footer.md
Replaces discord invite links with the official website's discord link.
> Replace discord invite links with runelite.net link

- Info-Panel.md
- Info-panel.md
- Small update to the info.
- Changes to ``Info Panel`` capitalization and some other minor changes.
> Info Panel: update information

- Chat-Commands.md
Added huey and amox to chat-commands.
Wasn't really sure where they best fit in, so I used the opportunity to change the order of chaos ele, crazy arch, deranged arch (which did not make sense to begin with).
Now it's:
slayer monsters
varlamore pt2 bosses for noobs
archeologist boss for noobs
wilderness version of the archeologist boss for noobs, drops chaos ele pet
chaos ele (drops chaos ele pet)
other wilderness bosses
> Chat-Commands: add amoxliatl and hueycoatl short names

- Chat-Commands.md
I hate markdown. Also, I could've sworn I included these line breaks.
> Chat-Commands: fix line breaks

- Chat-Commands.md
Implementation PR: https://github.com/runelite/runelite/pull/18537
* Larran's small chest
* Larran's big chest
* Brimstone chest
* crystal chest
> chat commands: add chests

- Rejected-or-Rolled-Back-Features.md
This has come up a few times, so it seems like a good idea to list in rejected features so we have something to point to.
> rejected-features: add plugins which allow pasting into chat
