runelite/wiki

- VarPlayers,-VarBits,-and-VarClients.md
The `getVar` seems to be deprecated. Replace it with `getVarbitValue` and add calls for the other var types.
> Update deprecated reference

- Change-DPI-Scaling-(Windows).md
Saved me after a couple of cropped screenshots, thought it might be worth mentioning here.
> DPI scaling override for jar launcher on windows

- Remove-Java-Memory-Limit.md
Here's a [link to a preview](https://github.com/aHooder/runelite-wiki/blob/guide-remove-java-options/Remove-Java-Memory-Limit.md).
> Add instructions for deleting `_JAVA_OPTIONS` env variable

- Building-with-IntelliJ-IDEA.md
This seems like the simplest approach for pushing the `mvn clean install -U` command towards the user. 
Since it fixes various issues when building the client, putting it in the most blatant spot seems like the best approach, even if a few people whom the command would not resolve there issue, end up also running it.
Fixes #23
> Better indicate running `mvn clean install -U` as a fix when building the client

- Rejected-or-Rolled-Back-Features.md
As far as I know, prayer re-ordering was the only thing currently listed, that was removed since the last update in March.
> Update rejected features page to current statement

- Code-Conventions.md
A few weeks ago someone came into #development and commented on the fact that the link to the codestyle no longer worked. In this case the link does still work, but is hosted on a non-secure website.
During said conversation, discussion was held about native codeStyle files on the main project, but until that is done, this should be updated to host the codestyle XML on Github.
> Host Code Convention formatting XML on the wiki

- Code-Conventions.md
See: https://github.com/runelite/runelite/wiki/Code-Conventions#imports
The modification to the `Names count to use static imports with '*'` field, described in the `## Imports` section didn't match the screenshot below it (https://i.imgur.com/XlJzIKv.png).
Talking to Adam on Discord to figure out which was the correct setting, he said:
> usually 999
> the problem is if it star imports eg ItemID or something, intellij typically gets sluggish because the file has so many fields
> and so you want to make it avoid that
Warning: This is my first PR, so please let me know if I've missed any steps in the pull request process.
> Fix minor inconsistency in Code-Conventions.md IntelliJ Imports section

- Time-Tracking.md
- World-Hopper.md
Documents both `::commands` that are not restricted in their usage by dev mode
Closes #45
> document `::commands`

- Rejected-or-Rolled-Back-Features.md
2 different touchscreen and one controller plugin were all PR'd in a short window, and another user came into the discord asking about touchscreen issues recently, so I've gone ahead and added a note rejecting them as a hub plugin.
> Rejected-Features: add touchscreen/controller plugins

- Slayer.md
These issues were resolved since the slayer plugin no longer tracks/stores task information locally but instead relies on vars.
> slayer: update page to reflect changes in task tracking

- Chat-Commands.md
This PR:
- Adds the missing boss aliases.
- https://github.com/runelite/wiki/pull/59 and https://github.com/runelite/wiki/pull/77 are not included in this PR!
- Sorts the boss aliases.
- This sorting is quite subjective. I've tried to add my reasoning to the end of this comment.
- I'd probably add the lunar chests after barrows.
- Adds the missing agility course aliases.
- Sorts the agility course aliases.
- Sorted based on their initial unlock level, then alphabetically, i.e. https://oldschool.runescape.wiki/w/Agility/Level_up_table
- Adds aliases for misc. activities (herbi, skilling "bosses"/minigames).
- Adds the missing aliases for skills.
- Sorted according to the [ingame skill interface](https://oldschool.runescape.wiki/images/Skills_tab.png?5bd59).
- Adds the adventure log or …
> chat commands: rework aliases

- Building-with-IntelliJ-IDEA.md
Adds a note specifying that the guide is for core development and directs hub devs to the Developer Guide.
There have been a fair number of people trying to use this guide for hub development so the note seemed warranted
> Building with IntelliJ: Add note about being for core development

- Rejected-or-Rolled-Back-Features.md
As mentioned by Adam [here](https://togithub.com/runelite/plugin-hub/pull/6200#issuecomment-2183182026).
> Rejected-Features: add plugins which expose player information over http to list of features not being considered

- Timers.md
Removes the outdated list of available timers. We're not going to keep updating this list, so it'll likely always be outdated. Additionally, there's no reason for this list to exist; you can perfectly see it in the timers config, and the config contains way more useful info than this list.
> timers: remove outdated list of available timers

- Chat-Commands.md
Lunar Chest and (regular) gauntlet was on the same line.
> Add missing linebreak after lunar chest.

- Building-with-IntelliJ-IDEA.md
Add link to wiki page that explains the process to enable the VM Options text field next to the troubleshooting advice that instructs the users to use the VM Options text field.
Add clarifying information for ABI acronym and how to know when an ABI change has been made.
> Update Pluginhub troubleshooting section

- Plugin takeover policy.md
i did this from the webui so the whitespace change i can't see has to stay
> Plugin-takeover-policy: mention the need to enable issues on the fork

- Building-with-IntelliJ-IDEA.md
IntelliJ on macOS no longer refers to its settings menu as `Preferences`
> update macOS build instructions

- Disable-Hardware-Acceleration.md
don't show a checkbox that wouldn't be checked, otherwise users will think they need to also toggle it
same thing I did in #34
> Disable-Hardware-Accel: use an image without debug checked

- Idle-Notifier.md
Can revert [`a330d32` (#142)](https://github.com/runelite/wiki/pull/142/commits/a330d326cbd3a77d45f9b8e5981d5a41a127e9c9) if you love the numbers.
I modified as few of the current ways to phrase things as possible, happy to reword things as you see fit.
> Update Idle Notifier documentation

- RuneLite-Launcher-Configuration.md
Specifies that a new profile will be created if `--profile` is passed with a value that doesn't match the name of an existing profile.
This came up in the support channel recently and seemed like something worth documenting for the future.
> RuneLite-Launcher-Configuration: clarify profile argument behavior

- Rejected-or-Rolled-Back-Features.md
Adds a section which advises authors of in-code behaviors which we've historically disallowed.
> rejected: add section about forbidden language features
